version: "3"
services:
  mariadb:
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: discord_data
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql

  orion_client:
    build: .
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - mariadb