name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./discord/
        push: true
        tags: |
          ghcr.io/orion_client:latest
          ghcr.io/orion_client:${{ github.sha }}
        dockerfile: Dockerfile
      env:
        DOCKER_USERNAME: ${{ secrets.MY_GITHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.MY_GITHUB_TOKEN }}
